namespace Najs.Routing {
  export type HttpMethod =
    | 'CHECKOUT'
    | 'COPY'
    | 'DELETE'
    | 'GET'
    | 'HEAD'
    | 'LOCK'
    | 'MERGE'
    | 'MKACTIVITY'
    | 'MKCOL'
    | 'MOVE'
    | 'M-SEARCH'
    | 'NOTIFY'
    | 'OPTIONS'
    | 'PATCH'
    | 'POST'
    | 'PURGE'
    | 'PUT'
    | 'REPORT'
    | 'SEARCH'
    | 'SUBSCRIBE'
    | 'TRACE'
    | 'UNLOCK'
    | 'UNSUBSCRIBE'
}
